DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');
SELECT * FROM TEST ORDER BY ID;
UPDATE TEST SET NAME='Hi' WHERE ID=1;
DELETE FROM TEST WHERE ID=2;

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT auto_increment, NOMBRE VARCHAR(255),APELLIDO VARCHAR(255),TELEFONO VARCHAR(255));
CREATE TABLE TEST(ID INT auto_increment PRIMARY KEY, NOMBRE VARCHAR(255),APELLIDO VARCHAR(255),TELEFONO VARCHAR(255));
INSERT INTO TEST (NOMBRE, APELLIDO, TELEFONO) VALUES('Hello','k','123123');