DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255));
INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World');
SELECT * FROM TEST ORDER BY ID;
UPDATE TEST SET NAME='Hi' WHERE ID=1;
DELETE FROM TEST WHERE ID=2;

DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT auto_increment, NOMBRE VARCHAR(255),APELLIDO VARCHAR(255),TELEFONO VARCHAR(255));
CREATE TABLE TEST(ID INT auto_increment PRIMARY KEY, NOMBRE VARCHAR(255),APELLIDO VARCHAR(255),TELEFONO VARCHAR(255));
INSERT INTO TEST (NOMBRE, APELLIDO, TELEFONO) VALUES('Hello','k','123123');


DROP TABLE IF EXISTS TEST;
CREATE TABLE SISTEMASQL(ID INT auto_increment PRIMARY KEY, NOMBRE VARCHAR(255),APELLIDO VARCHAR(255),TELEFONO VARCHAR(255),
CALLE VARCHAR(255),NUMEXT VARCHAR(255),NUMINT VARCHAR(255),COLONIA VARCHAR(255),DELEGACION VARCHAR(255),
CP VARCHAR(255),ECALLE VARCHAR(255),YCALLE VARCHAR(255),COLOR VARCHAR(255),
ALERGIA VARCHAR(255),INTOLERANCIA VARCHAR(255),REGIMEN VARCHAR(255),
EDAD VARCHAR(255),CUMPLE VARCHAR(255),PREFERENCIA VARCHAR(255),INSTAGRAM VARCHAR(255),FB VARCHAR(255),
CORREO VARCHAR(255),NOTAS VARCHAR(255));

INSERT INTO SISTEMASQL (NOMBRE, APELLIDO, TELEFONO,CALLE,NUMEXT,NUMINT,COLONIA,DELEGACION,CP,
ECALLE,YCALLE,COLOR,ALERGIA,INTOLERANCIA,REGIMEN,EDAD,CUMPLE,PREFERENCIA,INSTAGRAM,FB,CORREO,
NOTAS) VALUES('nomm','apelli','123123','uxmal','648','sin','colon','bj','0365','matrias','chich',
'blan','ninguna','ninguna','vegana','21','13ene','sushi','ima','asd','asd@','asdasdasd');

UPDATE SISTEMASQL SET REGIMEN='VEGANO' WHERE ID=1;

INSERT INTO SISTEMASQL (NOMBRE, APELLIDO, TELEFONO,CALLE,NUMEXT,NUMINT,COLONIA,DELEGACION,
CP,ECALLE,YCALLE,COLOR,ALERGIA,INTOLERANCIA,REGIMEN,EDAD,CUMPLE,PREFERENCIA,INSTAGRAM,
FB,CORREO,NOTAS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

